[font]

normal = { family = "IBM Plex Mono" }
size = 16

[window]

dimensions = { columns = 120, lines = 40 }
dynamic_padding = true

[keyboard]

bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[mouse]

hide_when_typing = true

[general]

working_directory = "D:/funk0"

[terminal]

shell = "cmd.exe"
