[font]

normal = {family = "IBM Plex Mono"}
size = 18

[window]

dimensions = { columns = 100, lines = 36 }
dynamic_padding = true

[keyboard]

bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[mouse]

hide_when_typing = true

[terminal]

shell = "fish"
